const momentChoice=(text,effects,result,legacy)=>({text,effects,result,legacy});
const FRIENDSHIP_MOMENTS=[
  {id:'aiko-rooftop',npcId:'aiko',scene:0,title:'The Unscheduled Rooftop',location:'Rooftop at sunset',text:'Aiko closes her planner and admits she scheduled this meeting without an agenda. The city lights come on below the academy.\n\n“I wanted one hour that did not need to become useful.”',choices:[
    momentChoice('Sit quietly and let the hour remain unmeasured.',{kindness:2,stress:-5,score:14},'Aiko watches the sky instead of the clock. “I may need practice at this.”','diplomat'),
    momentChoice('Tell her what you hope life after school feels like.',{courage:1,charisma:1,score:13},'The conversation becomes the first plan neither of you tries to optimize.','visionary'),
    momentChoice('Make a tiny agenda titled “Do absolutely nothing.”',{charisma:2,stress:-3,score:12},'She laughs, writes “completed” beside it, and keeps the page.','connector')
  ]},
  {id:'mina-dawn-track',npcId:'mina',scene:1,title:'Before the Starting Gun',location:'Track at dawn',text:'Mina meets you before sunrise for a final practice lap. No team, no crowd and no stopwatch—only cold air and the sound of shoes on the track.\n\n“Today I want to remember the running, not the result.”',choices:[
    momentChoice('Run beside her at a pace that allows conversation.',{fitness:1,kindness:1,score:14},'You finish with no official time and a story that lasts longer than any record.','champion'),
    momentChoice('Let her choose when the lap ends.',{reliability:1,stress:-4,score:12},'She stops halfway, looks at the sunrise, and decides that is enough.','steward'),
    momentChoice('Race the final straight with everything you have.',{fitness:2,courage:1,score:15},'Neither of you agrees who won. Both of you remember the grin.','champion')
  ]},
  {id:'rina-empty-gallery',npcId:'rina',scene:2,title:'After the Gallery Empties',location:'Festival gallery',text:'The visitors have gone. Rina leaves one spotlight on and asks you to walk through the exhibit as if nobody will ever review it.\n\n“Which piece feels most like us?”',choices:[
    momentChoice('Choose the unfinished mural.',{talent:1,kindness:1,score:14},'She adds the date in a corner but leaves the last shape open.','artist'),
    momentChoice('Choose the smallest sketch nobody noticed.',{kindness:2,score:13},'Rina frames it later under the title “Seen by One Person.”','artist'),
    momentChoice('Tell her the room itself is the artwork now.',{charisma:1,talent:1,score:13},'Your footsteps and laughter become the final performance.','connector')
  ]},
  {id:'emi-power-down',npcId:'emi',scene:3,title:'Power-Down Picnic',location:'Courtyard under the ginkgo tree',text:'Emi arrives with a paper map, mechanical pencil and a lunchbox labeled OFFLINE BACKUP. Her phone is switched off.\n\n“If something happens and nobody logs it, does it still count?”',choices:[
    momentChoice('Write one sentence each in a paper field log.',{intellect:1,talent:1,score:14},'The final page reads: “System stable. Friendship confirmed.”','builder'),
    momentChoice('Tell her the memory can belong only to you two.',{kindness:2,score:14},'Emi looks nervous, then relieved. “Private storage accepted.”','confidant'),
    momentChoice('Invent analog error messages for the picnic.',{charisma:2,stress:-4,score:12},'“ERROR: blanket contains too many crumbs” becomes a running joke.','connector')
  ]},
  {id:'hana-closed-desk',npcId:'hana',scene:4,title:'Peer Support Desk: Closed',location:'Empty homeroom',text:'Hana turns the peer-support sign from OPEN to CLOSED while you are still inside. She places two cups of tea on the desk.\n\n“Today nobody gets advice. We are allowed to just be tired.”',choices:[
    momentChoice('Share one thing you could not fix this year.',{kindness:2,courage:1,score:14},'Hana listens without turning the story into a task.','mentor'),
    momentChoice('Make a rule that both of you must accept help tomorrow.',{reliability:2,score:13},'She writes the rule on the back of the CLOSED sign.','steward'),
    momentChoice('Drink the tea in complete silence.',{stress:-7,kindness:1,score:12},'The quiet becomes the kindest conversation of the week.','confidant')
  ]},
  {id:'ren-empty-gym',npcId:'ren',scene:5,title:'One Last Empty Gym',location:'Gym after lights-out',text:'Ren turns on only the scoreboard. It shows 00–00. He bounces the ball once and lets the echo fade.\n\n“This is how every game begins before people decide what it means.”',choices:[
    momentChoice('Take alternating shots until one of you misses twice.',{fitness:2,score:14},'The rules change three times and the final score is deliberately forgotten.','champion'),
    momentChoice('Ask what he wants to be remembered for besides winning.',{charisma:1,kindness:1,score:14},'His answer is simple: “The pass people were brave enough to take.”','leader'),
    momentChoice('Sit on the center line and talk about fear.',{courage:2,stress:-3,score:13},'The empty gym makes honesty feel less public.','confidant')
  ]},
  {id:'haru-last-song',npcId:'haru',scene:6,title:'The Song After the Encore',location:'Music room',text:'Haru plays a melody he never submitted for any festival. It has no title and stops before the final chord.\n\n“I think finishing it would make it belong to everyone.”',choices:[
    momentChoice('Ask him to leave the final chord unwritten.',{talent:2,score:14},'The unfinished song becomes yours to remember rather than theirs to judge.','artist'),
    momentChoice('Hum a harmony without recording it.',{talent:1,kindness:1,score:14},'For one minute the room holds a song that exists nowhere else.','confidant'),
    momentChoice('Give it a ridiculous private title.',{charisma:2,score:12},'“Cafeteria Moonlight Sonata” is never spoken in public.','connector')
  ]},
  {id:'daichi-dead-air',npcId:'daichi',scene:7,title:'Thirty Seconds of Dead Air',location:'Student radio booth',text:'Daichi switches off the broadcast microphone. The ON AIR sign goes dark, and for once he has no audience.\n\n“I talk because silence gives people time to decide I am not interesting.”',choices:[
    momentChoice('Tell him silence is not a verdict.',{kindness:2,score:14},'He lets thirty seconds pass without filling them. Nothing breaks.','confidant'),
    momentChoice('Ask what he would say if nobody could repeat it.',{courage:1,charisma:1,score:14},'His answer is quiet, sincere and free of punchlines.','connector'),
    momentChoice('Record a fake weather report for only the two of you.',{charisma:2,stress:-4,score:12},'Forecast: ninety percent chance of friendship, severe snack warnings.','connector')
  ]},
  {id:'kenji-coop-ending',npcId:'kenji',scene:8,title:'The Cooperative Ending',location:'Library game table',text:'Kenji brings a strategy game with no winner. The players either repair the city together or all lose.\n\n“I thought competition was the only honest way to measure improvement.”',choices:[
    momentChoice('Let him lead, then question one risky plan.',{intellect:2,score:14},'He changes course without treating the change as defeat.','builder'),
    momentChoice('Choose the weaker role and make it useful.',{reliability:1,kindness:1,score:14},'The final turn succeeds because every role mattered.','leader'),
    momentChoice('Celebrate the mistakes that created the solution.',{charisma:1,intellect:1,score:13},'Kenji writes “productive failure” in the margin of the score sheet.','builder')
  ]},
  {id:'sora-empty-podium',npcId:'sora',scene:9,title:'The Empty Podium',location:'Assembly hall',text:'Sora stands behind the debate podium after the hall empties. He removes the winning speech from the lectern.\n\n“I was right. I am not sure I was generous.”',choices:[
    momentChoice('Help rewrite the argument for someone who disagrees.',{intellect:1,kindness:1,score:14},'The new version is less devastating and far more persuasive.','diplomat'),
    momentChoice('Tell him conviction and humility can share a sentence.',{courage:1,charisma:1,score:14},'He writes that line at the top of next year’s notes.','diplomat'),
    momentChoice('Ask what changed his own mind this year.',{kindness:2,score:13},'His answer includes your name.','confidant')
  ]}
];

const incidentChoice=(text,effects,result)=>({text,effects,result});
const CAMPUS_INCIDENTS=[
  {id:'rain-umbrella',title:'One Umbrella Short',slots:['break','lunch'],weather:['rain'],minMonth:1,text:'A first-year stands at the courtyard doors, pretending the rain is temporary. Every umbrella rack is empty.',choices:[incidentChoice('Share your umbrella and walk slowly.',{kindness:2,energy:-2,score:7},'The walk takes longer, but the student arrives dry enough to stop pretending.'),incidentChoice('Organize a three-person umbrella relay.',{charisma:1,reliability:1,score:8},'The system is absurd, effective and immediately copied.'),incidentChoice('Ask the office for a spare.',{reliability:2,score:6},'The spare umbrella is ugly, enormous and exactly what was needed.')]},
  {id:'wind-posters',title:'Poster Storm',slots:['break','free'],weather:['wind'],minMonth:1,text:'A gust tears club posters from the notice board and sends them racing down the hallway.',choices:[incidentChoice('Catch the posters before sorting them.',{fitness:1,reliability:1,score:7},'You recover every poster except one mysterious flyer for a club that does not exist.'),incidentChoice('Turn the cleanup into a quick team game.',{charisma:2,score:7},'Ten students join before they realize they are volunteering.'),incidentChoice('Redesign the board so it survives next time.',{intellect:1,talent:1,score:8},'Emi approves the new clips. Rina approves the spacing.')]},
  {id:'snow-path',title:'The Icy Shortcut',slots:['arrival','break'],weather:['snow'],minMonth:1,text:'The fastest path to the entrance has frozen into a very convincing trap.',choices:[incidentChoice('Redirect students and mark the hazard.',{reliability:2,score:8},'Nobody falls, which is less dramatic and much better.'),incidentChoice('Help spread grit with the custodian.',{fitness:1,kindness:1,energy:-4,score:8},'The path becomes safe one careful shovel at a time.'),incidentChoice('Film a safety announcement with Daichi.',{charisma:2,score:7},'His reenactment is physically impossible but memorable.')]},
  {id:'clear-lost-note',title:'A Note With No Name',slots:['break','lunch'],weather:['clear','cloudy'],minMonth:1,text:'You find a folded note beside the fountain: “I am trying. Please do not give up on me.” There is no name.',choices:[incidentChoice('Leave it with the counselor and protect the privacy.',{reliability:2,kindness:1,score:9},'The note reaches someone trained to help without becoming hallway gossip.'),incidentChoice('Post a general message about support resources.',{charisma:1,kindness:1,score:8},'Nobody is singled out, but several students take a card.'),incidentChoice('Add an anonymous reply and leave it nearby.',{talent:1,kindness:1,score:7},'The reply reads: “Trying counts. You are not invisible.”')]},
  {id:'cafeteria-allergen',title:'The Unlabeled Tray',slots:['lunch'],weather:['clear','cloudy','rain','wind','snow'],minMonth:2,text:'A cafeteria tray was moved without its allergy label. The lunch rush is already forming.',choices:[incidentChoice('Stop the line and ask staff to verify it.',{courage:1,reliability:2,score:10},'The delay earns a few complaints and prevents a serious mistake.'),incidentChoice('Create a temporary warning sign.',{talent:1,reliability:1,score:8},'The bright sign is impossible to miss while staff confirm the ingredients.'),incidentChoice('Help reorganize the serving area.',{intellect:1,energy:-3,score:8},'The labels are moved above the trays where they cannot be separated.')]},
  {id:'library-whisper',title:'The Whisper Chain',slots:['break','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:2,text:'A false rumor about a teacher is moving through the library in whispers, gaining details every time.',choices:[incidentChoice('Ask where the claim started.',{intellect:1,courage:1,score:8},'The chain leads to a misunderstood calendar notice, not a scandal.'),incidentChoice('Correct only what you can verify.',{reliability:2,score:9},'The rumor loses momentum because you refuse to replace it with another guess.'),incidentChoice('Invite the group to ask the teacher directly.',{charisma:1,courage:1,score:8},'The answer is ordinary, which is exactly what the hallway needed.')]},
  {id:'gym-shoes',title:'The Missing Indoor Shoes',slots:['break','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:2,text:'A student has PE next and cannot find their indoor shoes. Someone moved the entire class rack as a joke.',choices:[incidentChoice('Help return every pair in order.',{reliability:2,energy:-3,score:8},'The joke ends before anyone has to perform embarrassment.'),incidentChoice('Ask Coach Kondo for a temporary pair.',{charisma:1,kindness:1,score:7},'The borrowed pair is two sizes too large but safe.'),incidentChoice('Turn the search into a quiet class effort.',{kindness:1,charisma:1,score:8},'The shoes reappear without naming or humiliating the joker.')]},
  {id:'robot-delivery',title:'Runaway Book Cart',slots:['break','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:3,text:'Emi’s automated book cart leaves the library, turns into the hallway and begins politely announcing that everyone is an obstacle.',choices:[incidentChoice('Block the corridor and guide it home.',{courage:1,intellect:1,score:8},'The cart returns without injuring anything except Emi’s pride.'),incidentChoice('Use its voice commands to redirect it.',{intellect:2,score:9},'“RETURN TO BASE” works after “PLEASE” unexpectedly fails.'),incidentChoice('Walk beside it and apologize to pedestrians.',{charisma:2,score:7},'The incident becomes a campus tour rather than a disaster.')]},
  {id:'art-paint',title:'Blue Paint, White Uniform',slots:['break','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:3,text:'A bucket tips in the art room. Blue paint spreads toward a stack of finished costumes while one student freezes in panic.',choices:[incidentChoice('Move the costumes first.',{courage:1,reliability:1,energy:-3,score:9},'The costumes survive. Your shoes become abstract art.'),incidentChoice('Give the frozen student one clear task.',{charisma:1,kindness:1,score:9},'“Grab towels” is small enough to break the panic.'),incidentChoice('Use cardboard to contain the spill.',{intellect:1,talent:1,score:8},'Rina later calls the improvised barrier “functional sculpture.”')]},
  {id:'radio-mic',title:'The Microphone Is Live',slots:['break','lunch'],weather:['clear','cloudy','rain','wind','snow'],minMonth:3,text:'The student-radio microphone is live while two hosts privately complain about a classmate.',choices:[incidentChoice('Cut the channel immediately.',{courage:1,reliability:2,score:10},'Only half a sentence reaches the hallway. The apology reaches all of it.'),incidentChoice('Signal the hosts without shouting.',{charisma:1,reliability:1,score:8},'Daichi sees your frantic mime and finds the mute switch.'),incidentChoice('Help write a direct private apology.',{kindness:2,score:9},'The classmate receives accountability without another public performance.')]},
  {id:'exam-pages',title:'Pages in the Wind',slots:['break'],weather:['wind'],minMonth:4,text:'A stack of marked practice exams escapes an open window. Names and scores are visible as pages scatter.',choices:[incidentChoice('Collect them face-down.',{reliability:2,kindness:1,score:10},'Privacy survives the windstorm.'),incidentChoice('Create a human screen while others collect.',{courage:1,charisma:1,score:9},'Nobody gets an accidental look at someone else’s result.'),incidentChoice('Ask Mr. Mori to digitize future copies.',{intellect:2,score:8},'He agrees after catching page seventeen in a shrub.')]},
  {id:'garden-nest',title:'A Nest in the Planter',slots:['break','free'],weather:['clear','cloudy'],minMonth:4,text:'Garden duty stops when a small bird’s nest is discovered inside the planter scheduled for replanting.',choices:[incidentChoice('Reroute the garden plan around it.',{kindness:2,intellect:1,score:9},'The new design protects the nest and looks better than the original.'),incidentChoice('Mark a quiet boundary.',{reliability:2,score:8},'Students give the planter space without turning it into an attraction.'),incidentChoice('Ask the science teacher for guidance.',{intellect:1,reliability:1,score:8},'The advice keeps both the birds and the garden safe.')]},
  {id:'debate-card',title:'The Anonymous Question',slots:['lunch','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:5,text:'An anonymous debate question attacks a student’s identity rather than their argument. Sora is deciding whether to read it aloud.',choices:[incidentChoice('Remove it and explain the standard publicly.',{courage:2,reliability:1,score:10},'The forum stays open without treating cruelty as debate.'),incidentChoice('Rewrite the underlying policy question fairly.',{intellect:2,kindness:1,score:10},'The difficult issue remains, but the target disappears.'),incidentChoice('Ask the affected student what feels safe.',{kindness:2,score:10},'They choose a boundary and remain in control of the room.')]},
  {id:'club-room',title:'Double-Booked Club Room',slots:['free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:5,text:'Two clubs arrive for the same room. Both have printed confirmation emails. Neither is willing to cancel.',choices:[incidentChoice('Split the room and coordinate noise.',{charisma:1,reliability:1,score:9},'The arrangement is imperfect but fair enough to work.'),incidentChoice('Find an unused alternative space.',{intellect:1,fitness:1,energy:-3,score:9},'One club moves to the courtyard and discovers better acoustics.'),incidentChoice('Ask both captains to compare priorities.',{courage:1,kindness:1,score:9},'The club with a deadline stays; the other receives first choice next week.')]},
  {id:'hallway-wheelchair',title:'The Blocked Ramp',slots:['arrival','break','lunch'],weather:['clear','cloudy','rain','wind','snow'],minMonth:5,text:'Delivery boxes have been left across the accessibility ramp while the main hallway is crowded.',choices:[incidentChoice('Clear the boxes immediately.',{fitness:1,reliability:2,energy:-3,score:10},'The ramp is open before anyone has to ask.'),incidentChoice('Redirect deliveries and mark the no-storage zone.',{charisma:1,reliability:1,score:9},'The fix lasts beyond today.'),incidentChoice('Call facilities and remain until it is cleared.',{courage:1,kindness:1,score:9},'You refuse to treat access as somebody else’s later problem.')]},
  {id:'power-study',title:'Power Out, Notes Open',slots:['free'],weather:['rain','wind'],minMonth:6,text:'The lights fail during a study session. Phones are low, the emergency lights are dim and an exam is tomorrow.',choices:[incidentChoice('Move the group near the courtyard windows.',{reliability:1,intellect:1,score:8},'Natural light and shared notes keep the session going.'),incidentChoice('Turn review into an oral quiz.',{charisma:1,intellect:1,score:9},'The blackout becomes the most focused session of the month.'),incidentChoice('End early and protect everyone’s energy.',{kindness:1,reliability:1,stress:-3,score:7},'Nobody studies well enough to justify staying unsafe.')]},
  {id:'festival-cash',title:'The Missing Donation Envelope',slots:['lunch','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:6,text:'A festival donation envelope is missing. Suspicion is already settling on the newest volunteer.',choices:[incidentChoice('Freeze the cash process and audit calmly.',{intellect:1,reliability:2,score:11},'The envelope is found inside a duplicate lockbox. The volunteer receives an apology.'),incidentChoice('Stop people from naming suspects.',{courage:2,kindness:1,score:10},'The search stays about the envelope instead of becoming a trial.'),incidentChoice('Reconstruct the handoff timeline.',{intellect:2,score:10},'The missing five minutes point to a simple storage mistake.')]},
  {id:'nickname-return',title:'The Nickname Returns',slots:['break','lunch'],weather:['clear','cloudy','rain','wind','snow'],minMonth:6,text:'An embarrassing nickname resurfaces in a group chat. Students laugh because they think the target is not present.',choices:[incidentChoice('Say clearly that the nickname is retired.',{courage:2,kindness:1,score:10},'The laughter stops without requiring the target to defend themselves.'),incidentChoice('Redirect the chat and message the target privately.',{charisma:1,kindness:2,score:9},'They appreciate being checked on without being made into a scene.'),incidentChoice('Ask why the joke needs one person to lose.',{intellect:1,courage:1,score:9},'Nobody has a satisfying answer. That matters.')]},
  {id:'teacher-boxes',title:'Ms. Arai’s Book Boxes',slots:['free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:7,text:'Ms. Arai is moving donated books alone after insisting she does not need help.',choices:[incidentChoice('Carry half without making a speech.',{fitness:1,reliability:2,energy:-4,score:9},'She accepts after a theatrical sigh and saves you the best title.'),incidentChoice('Recruit a quiet five-minute team.',{charisma:1,kindness:1,score:9},'The boxes disappear before help can become an event.'),incidentChoice('Create a rolling cart route.',{intellect:2,score:8},'The solution prevents three future afternoons of carrying.')]},
  {id:'heat-water',title:'Too Proud for Water',slots:['break','lunch','free'],weather:['clear'],minMonth:7,text:'During an unusually hot day, a student refuses water because leaving practice would look weak.',choices:[incidentChoice('Normalize a team hydration break.',{charisma:1,fitness:1,score:10},'Everyone drinks, so nobody has to admit they needed it first.'),incidentChoice('Ask Coach Kondo to call the break.',{reliability:1,courage:1,score:9},'The instruction removes pride from the decision.'),incidentChoice('Offer water and sit down yourself.',{kindness:2,score:9},'The student follows without being singled out.')]},
  {id:'archive-photo',title:'The Photograph Without a Caption',slots:['break','free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:8,text:'An old academy photograph shows a student group nobody can identify. The caption card is blank.',choices:[incidentChoice('Interview alumni and rebuild the story.',{charisma:1,intellect:1,score:9},'Three names return to the archive, along with a story about a forgotten club.'),incidentChoice('Display it as “Names Still Being Found.”',{talent:1,kindness:1,score:8},'The honest caption invites information instead of inventing certainty.'),incidentChoice('Create a student archive project.',{reliability:1,intellect:1,score:9},'Future photographs begin collecting names while memories are fresh.')]},
  {id:'ranking-tears',title:'After the Board Updates',slots:['break','lunch'],weather:['clear','cloudy','rain','wind','snow'],minMonth:8,text:'A student sees their new ranking, walks behind the stairwell and tries not to cry.',choices:[incidentChoice('Sit nearby without asking for an explanation.',{kindness:2,stress:-2,score:9},'The silence gives them room to stop performing composure.'),incidentChoice('Remind them the board measures only part of a person.',{charisma:1,kindness:1,score:9},'They do not believe it immediately, but they keep listening.'),incidentChoice('Offer to review one achievable goal.',{reliability:1,intellect:1,score:9},'The next step becomes smaller than the whole ladder.')]},
  {id:'lost-child',title:'Community Day: Lost Child',slots:['lunch','free'],weather:['clear','cloudy','rain','wind'],minMonth:9,text:'During Community Day, a young visitor cannot find their family and is too frightened to speak clearly.',choices:[incidentChoice('Stay at eye level and ask simple questions.',{kindness:2,reliability:1,score:11},'A shoe color and a balloon lead to the right family.'),incidentChoice('Notify staff while keeping the child in one place.',{reliability:2,score:10},'The search moves outward without making the child move again.'),incidentChoice('Use the radio without announcing the child’s name.',{charisma:1,intellect:1,score:10},'The privacy-conscious message reaches the family quickly.')]},
  {id:'gala-dress',title:'The Borrowed Formalwear',slots:['free'],weather:['clear','cloudy','rain','wind','snow'],minMonth:10,text:'A student considers skipping the gala because they cannot afford formal clothes and do not want charity announced around them.',choices:[incidentChoice('Help create a private borrowing system.',{kindness:2,reliability:1,score:11},'Several students contribute without knowing who borrows what.'),incidentChoice('Propose a flexible dress code for everyone.',{courage:1,charisma:1,score:10},'The gala becomes more personal and less expensive.'),incidentChoice('Offer styling help with clothes they already own.',{talent:1,kindness:1,score:9},'The final look feels like them, not a disguise.')]}
];

const GRADUATION_LEGACIES=[
  {id:'crown',name:'The Crest Crown',subtitle:'Visible leadership with a human center',description:'You reached the top without treating the ladder as permission to look down.',color:'#e5b84b'},
  {id:'diplomat',name:'The Bridge Builder',subtitle:'Disagreement without humiliation',description:'Students remember that difficult rooms became more honest when you entered them.',color:'#87c9d8'},
  {id:'mentor',name:'The Open Door',subtitle:'Care that did not need applause',description:'Your legacy lives in students who learned they could ask for help before a crisis.',color:'#83b98b'},
  {id:'champion',name:'The Trusted Captain',subtitle:'Competition that made others braver',description:'You proved that excellence and generosity can share the same finish line.',color:'#d47a43'},
  {id:'artist',name:'The Living Canvas',subtitle:'A school made more expressive',description:'You left songs, images and moments that made ordinary hallways feel worth remembering.',color:'#e88ea4'},
  {id:'builder',name:'The Systems Mind',subtitle:'Better structures, fewer invisible problems',description:'You repaired more than machines. You made the school easier to navigate for the people after you.',color:'#4d76a8'},
  {id:'steward',name:'The Quiet Steward',subtitle:'Reliability as a form of respect',description:'The paths were clear, the plans were finished and people trusted promises with your name on them.',color:'#4d8b68'},
  {id:'connector',name:'The Campus Voice',subtitle:'Warmth across every circle',description:'You turned announcements, jokes and chance meetings into a sense that everyone belonged to one school.',color:'#c75b7a'},
  {id:'confidant',name:'The Keeper of Stories',subtitle:'Deep trust over broad recognition',description:'The most important parts of your school life were never posted on the ranking board.',color:'#8d74b8'},
  {id:'leader',name:'The Shared Spotlight',subtitle:'Leadership that created room',description:'Your strongest decisions made other people more visible, capable and willing to lead.',color:'#f0b34f'},
  {id:'visionary',name:'The Future Draft',subtitle:'Ambition with imagination',description:'You left Sakura Crest asking not only who should lead next, but what the school could become.',color:'#6aa4c8'},
  {id:'constant',name:'The Everyday Legend',subtitle:'A thousand useful ordinary choices',description:'No single event explains your legacy. It was built through days when you simply kept showing up.',color:'#b8c6d8'}
];

const EXAM_BANK = [
  {subject:'Mathematics',prompt:'The festival budget is 1,200 credits. Decorations use 35%. How many credits remain?',options:['420','650','780','840'],correct:2},
  {subject:'Literature',prompt:'Which response best supports a theme with evidence?',options:['Repeat the title','Quote a scene and explain its meaning','Summarize every chapter','Describe the cover'],correct:1},
  {subject:'Social Studies',prompt:'A fair student-council decision should begin by…',options:['Choosing the loudest idea','Hiding the budget','Hearing affected groups','Skipping the vote'],correct:2},
  {subject:'Science',prompt:'Which habit makes an experiment easier to trust?',options:['Changing two variables','Recording every result','Ignoring failed trials','Guessing missing data'],correct:1},
  {subject:'Mathematics',prompt:'A relay team improves from 80 seconds to 68 seconds. What is the improvement?',options:['8 seconds','10 seconds','12 seconds','14 seconds'],correct:2},
  {subject:'Literature',prompt:'Dramatic irony occurs when…',options:['The audience knows more than a character','Every character agrees','A poem has no rhythm','The ending is cheerful'],correct:0},
  {subject:'Social Studies',prompt:'The strongest mediation statement is…',options:['You always ruin things','Let us name the shared problem first','I refuse to listen','The ranking proves I am right'],correct:1},
  {subject:'Science',prompt:'Why repeat a measurement?',options:['To make the report longer','To reduce random error','To guarantee the preferred answer','To avoid recording units'],correct:1}
];

const EXAM_SEASONS = Array.from({length:8},(_,index)=>{
  const year=Math.floor(index/2)+1,final=index%2===1,month=final?12:6,offset=(index*3)%EXAM_BANK.length;
  return {
    id:`y${year}-${final?'final':'midterm'}`,
    year,month,
    title:`Year ${year} ${final?'Final Examinations':'Midterms'}`,
    subtitle:final?'A full-year academic review.':'The first major academic checkpoint.',
    questions:Array.from({length:4},(_,q)=>EXAM_BANK[(offset+q)%EXAM_BANK.length]),
    rankWeight:final?1.3:1,
    legacy:final?'scholar':'steady'
  };
});

const WEEKEND_OUTINGS = [
  {id:'bookshop',name:'Old Town Bookshop',stat:'intellect',energy:8,stress:-12,description:'Browse used books and trade recommendations over cocoa.',partners:['emi','sora','kenji']},
  {id:'river_run',name:'Riverside Training',stat:'fitness',energy:-12,stress:-8,description:'A relaxed practice session where conversation matters more than pace.',partners:['mina','ren']},
  {id:'art_market',name:'Weekend Art Market',stat:'talent',energy:-4,stress:-12,description:'Sketch stalls, collect color ideas and help a nervous young performer.',partners:['rina','haru']},
  {id:'community_cafe',name:'Community Café Shift',stat:'kindness',energy:-8,stress:-6,description:'Volunteer together and quietly make the busiest table feel welcome.',partners:['hana','aiko']},
  {id:'arcade',name:'Retro Arcade Afternoon',stat:'courage',energy:-6,stress:-15,description:'Co-op games, harmless rivalry and one spectacularly difficult rhythm cabinet.',partners:['daichi','kenji','emi']},
  {id:'museum',name:'City History Museum',stat:'reliability',energy:-3,stress:-10,description:'Follow a clue trail through local history and keep the group on schedule.',partners:['aiko','sora','hana']},
  {id:'open_mic',name:'Open-Mic Evening',stat:'charisma',energy:-7,stress:-8,description:'Support a friend onstage—or step up for a short introduction yourself.',partners:['haru','rina','daichi']},
  {id:'garden_picnic',name:'Botanical Garden Picnic',stat:'kindness',energy:5,stress:-18,description:'A slow afternoon of snacks, photographs and honest conversation.',partners:['hana','mina','ren']}
];

const NEW_GAME_PLUS_PERKS = [
  {id:'remembered',name:'Remembered Bonds',description:'Begin with +2 Bond with every student.',apply:'relationships'},
  {id:'honors',name:'Honors Foundation',description:'Begin with +2 Intellect and +1 Reliability.',apply:'academics'},
  {id:'campus_star',name:'Campus Head Start',description:'Begin with 35 club XP and one club rank unlocked.',apply:'club'},
  {id:'calm_heart',name:'Calm Heart',description:'Begin with 20 less stress and +2 Kindness.',apply:'calm'}
];

const CAMPAIGN_PLATFORMS = [
  {id:'community',name:'Community First',stat:'kindness',legacy:'mentor',color:'#83b98b',description:'Peer support, welcoming events and practical help for students who feel unseen.'},
  {id:'achievement',name:'Raise the Standard',stat:'reliability',legacy:'steward',color:'#e5b84b',description:'Better study support, transparent planning and dependable student representation.'},
  {id:'creativity',name:'A School With a Voice',stat:'talent',legacy:'visionary',color:'#e88ea4',description:'More showcases, student media and room for every club to share its work.'},
  {id:'innovation',name:'Build Tomorrow',stat:'intellect',legacy:'builder',color:'#87c9d8',description:'Smarter systems, inclusive technology and student-led solutions to daily problems.'}
];

const questions = [
  {
    prompt:'Two clubs request the same hall on the same afternoon. What do you do first?',
    options:['Give it to the higher-ranked club.','Bring both captains together and publish a fair rotation.','Cancel both bookings until the argument stops.'],
    correct:1,
    explanation:'Transparent compromise earns more trust than status or avoidance.'
  },
  {
    prompt:'A rumor about a first-year student is spreading quickly. Your response?',
    options:['Correct the facts privately, support the student and address the pattern publicly.','Ignore it so the story loses energy.','Name the suspected source during assembly.'],
    correct:0,
    explanation:'Protecting the student while addressing the behavior is firm without becoming punitive.'
  },
  {
    prompt:'The festival budget is smaller than expected. Which principle guides the decision?',
    options:['Keep the most visible attractions at any cost.','Divide every amount equally, even when needs differ.','Publish the limits, protect safety and access, then invite clubs to redesign together.'],
    correct:2,
    explanation:'Good leadership makes constraints visible and asks people to solve them together.'
  }
];

const LEADERSHIP_ELECTIONS = [
  {id:'year1-representative',year:1,month:9,day:17,title:'First-Year Representative Election',subtitle:'Earn a place at the student council table.',opponent:'A confident upper-form nominee',threshold:72,questions},
  {id:'year2-committee',year:2,month:9,day:17,title:'Student Activities Committee Election',subtitle:'Turn a good reputation into a workable plan.',opponent:'The incumbent events coordinator',threshold:80,questions},
  {id:'year3-vice-president',year:3,month:9,day:17,title:'Student Council Vice-Presidential Election',subtitle:'Balance ambition, fairness and the pressure of the ranking board.',opponent:'A nationally recognized debate finalist',threshold:88,questions},
  {id:'year4-president',year:4,month:9,day:17,title:'Student Council Presidential Election',subtitle:'Ask the school to trust the person you became over four years.',opponent:'The strongest leadership candidate in Sakura Crest',threshold:96,questions}
];
